const studentsByClass = {
    3: [
        "Abhiraj Prashant Suryawanshi",
"Abila Habib Khan",
"Ahemad Ali Mohammad Altaf Lulaniya",
"Ajinkya Rahul Jondhale",
"Akshara Arjun Gangthare",
"Anurag Ashish Jondhale",
"Anvaya Kapil Shiradkar",
"Anzar Mohammad Amjad Shaikh",
"Arav Arvind Gajbhar",
"Arav Sudhakar Jamdade",
"Arnesh Dinesh Bharne",
"Arohi Kailas Khandare",
"Avishakar Ajay Katke",
"Ayesha Zafar Khan",
"Ayush Govind Badad",
"Dishanya Sandeep Jondhale",
"Haziq Majid Shaikh",
"Kunal Siddharth Ghodke",
"Marya Maryam Sk. Sameer Hussain",
"Nandini Kailash Harale",
"Priyal Rajesh Manwate",
"Rajnandini Vishal Awachar",
"Ritesh Devidas Latpate",
"Rutvij Pradeep Sugandhe",
"Samrat Manoj Kamble",
"Sejal Satish More",
"Shareque Khan Ajmal Khan",
"Shravani Sukdhadey Dhongde",
"Shreyash Vishwanath Ambhure",
"Shrusti Hanmant Sasane",
"Snehal Sanjay Suryawanshi",
"Somya Amol Dhadve",
"Syed Affan Syed Asef",
"Vivan Amol Panditkar"

        // Add more students for Class 3
    ],
    4: [
        "Aaroh Mahesh Rode",
"Abdul Rehman Abdul Aziz",
"Abdulla Akhil Ahmed",
"Aditi Rajesh Gaikwad",
"Ajinkya Milind Ghusale",
"Anushka Ashok Ranveer",
"Arhant Tushar Awasarmal",
"Arvind Gulabrao Sawant",
"Ashita Arvind Gajbhar",
"Ayush Dilip Malsaminder",
"Bouddhik Rajratan Shiradkar",
"Muhammad Hashir Abdulla",
"Pranav Umesh Sonawane",
"Prasenjeet Ganesh Ubale",
"Pratap Prakash Walke",
"Pratik Pramod Munde",
"Pruthviraj Punjaji Parve",
"Rashi Kailash Ubale",
"Rutuja Tushar Narwade",
"Sakshi Dulbaji Suryawanshi",
"Sandisha Siddharth Sawant",
"Shweta Harishchandra Waghmare",
"Siddharth Milind Pradhan",
"Swara Sanjeev Jadhav",
"Swara Tulshiram Kashinde",
"Syed Ibrahim Syed Ather",
"Syed Maaz Syed Imran",
"Syed Muzammil Asif Inamder",
"Syed Taha Syed Jameel Ahmed Hashmi",
"Tanishka Gajanan Waghmare",
"Vedant Nitin Ingole",
"Viraj Arvind Vitthalkar"
        // Add more students for Class 4
    ],
    5: [
       "Aarohi Subhash Dhabale",
"Adiyan Amjad Khan",
"Anas Mohasin Shaikh",
"Aryan Rahul Vairat",
"Bankar Kranti Vitthal",
"Darsh Prasanna Kate",
"Dhairya Rupesh Wahule",
"Dipke Sarthak Rajaram",
"Hanwate Utkarsh Prasannajit",
"Kagda Aditya Jogindarsingh",
"Khan Alishba Habib",
"Kurhade Dhiraj Yogeshwar",
"Kurhade Niraj Yogeshwar",
"Mohammad Afif Mohammad Aslam",
"Mohammad Amanuddin Kazi",
"Mohammad Farhanuddin Kazi",
"Mundhe Ansh Aniket",
"Patange Swaraj Sachin",
"Salve Aarohi Raju",
"Salve Naman Gautam",
"Sanchi Ganesh Kharat",
"Shaikh Amaan Shaikh Zahed",
"Shaikh Iram",
"Shaikh Zara Fatema Shaikh Hameed",
"Shravani Shankar Shinde",
"Swara Ganesh Kharat",
"Tak Ishita Rahul",
"Tareq Khan Ajmal Khan Pathan",
"Zainab Sarwari"
        // Add more students for Class 5
    ],
    6: [
       "Abdul Nafey Abdul Tahseen",
"Akib Moin Altaf Lulaniya",
"Alane Sharvari Vivek",
"Balkhande Tanvi Sanghratna",
"Bendre Siddhi Sunil",
"Boghani Sakina Fatima",
"Chate Atharva Venkatrao",
"Dhaware Harshdeep Sujit",
"Farooqui Mohammad Danishoddin",
"Jogdand Pranjal Sanghpal",
"Jondhale Chaitanya Rahul",
"Khandare Aryan Kailas",
"Khandare Iccha Ramakant",
"Kolhe Kartavya Kiran",
"Kulkarni Minakshi Venkatesh",
"Kute Sharvari Nitin",
"Landge Samradyani Nilesh",
"Maaz Khan Gaus Khan",
"Madiha Fatema Syed Asif",
"Mahamuni Shivam Vishwanath",
"Manwate Yuvraj Rajesh",
"Mirza Shehzan Baig",
"Mohammad Uzair Siddiqui",
"Paikrao Pushpwardhan Deepak",
"Pawan Ankush Tikhe",
"Raut Nimay Dindayal",
"Sasane Nagarjun Hanumant",
"Sayyad Abdul Malik",
"Shaikh Asjad Shaikh Amjad",
"Shaikh Mohammad Muzammil",
"Shreyas Sandip Khade",
"Soham Nitin Suradkar",
"Suryawanishi Anushka Prashant",
"Waghmare Pranjal Santukumar",
"Wakle Rishabh Wakle",
"Zain Ahmed Khan"
        // Add more students for Class 6
    ],
    7: [
     "Abdul Malik Abdul Aziz",
"Bankar Pawan Vitthal",
"Bharade Kalyani Milind",
"Farooqui Khansa Md Sarfarzuddin",
"Gaikwad Chaitanya Balasaheb",
"Ghodke Anikita Shivaji",
"Kalyani Ashok Shinde",
"Maske Sanchi Arun",
"Mohammad Saadaan Md. Zabi Ur Rehman",
"Narwade Kshitija Mangesh",
"Narwade Rajnandini Sachin",
"Poonam Shankar Shinde",
"Prerana Kapil Parre",
"Saksham Kishor Sahejrao",
"Sayeed Shaikh Iliyas",
"Shahane Sarthak Kiran",
"Sushant Shantipal Sable",
"Syed Mohammed Farjad Syed Muzaffar",
"Syed Yazzan Syed Mujib",
"Syeda Meraj Syed Jameel Ahmed",
"Thorat Abhay Sachin",
"Waghmare Gaurav Gajanan",
"Waghmare Pranit Ashok",
"Wakude Vaibhavi Rama"

        // Add more students for Class 7
    ],
    8: [
        "Aaftab Aaref Shaikh",
"Abdul Rehman Akil Ahmed Khan",
"Abdul Rehman Mazhar Khan",
"Aditi Milind Ghusale",
"Alishba Syed Anis",
"Arnav Nagorao Dudhgonde",
"Aryan Sopanrao Pote",
"Atharav Sudhakar Jamdade",
"Ayesh Humera Mir Karam Ali",
"Harshada Harishchandra Waghmare",
"Janhvi Amol Mahamuni",
"Jishan Farukh Shaikh",
"Kaab Ahmed Khan Iliyas Khan",
"Kaustubh Kailas Surwase",
"Kshipra Shrinivas Yannawar",
"Mansi Rahul Vairat",
"Mirza Faizan Baig",
"Mohammad Rayyan Sajed Qureshi",
"Nidhi Prasanna Kate",
"Prabodhini Siddharth Kokate",
"Pranav Omprakash Dahale",
"Riddhi Kerba Gaikwad",
"Rishabh Rajesh Sharma",
"Ritesh Chandrakant Bharade",
"Ritika Anil Hattiambire",
"Sambodhi Siddharth Raut",
"Samruddhi Kishor Dhoble",
"Sanchi Sanghratna Balkhande",
"Sayli Sanjay Surywanshi",
"Shaikh Rehan Shaikh Jawed",
"Shourya Shantanu Methekar",
"Siddhant Sambhaji Thorat",
"Siddharth Prakash Ranvir",
"Tanmay Rajkumar Mujmule",
"Tarequoddin Yousufoddin Mohammad"
        // Add more students for Class 8
    ]
};

const duties = [
    "Anchors",
    "Meditation",
    "Prayer",
    "Pledge",
    "Preamble",
    "School anthem",
    "Significance of the Day",
    "Thought of the Day",
    "G.K/News/Skit",
    "Speeches",
    "National Anthem",
    "Assembly Disperse"
];

const events = {
        "2024-06-01": ["Birth Anniversary of Dr. Baliram Hiray", "Event: Telangana Formation Day"],
        "2024-06-02": ["Birth Anniversary of Raja Ram Mohan Roy", "Event: International Sex Workers' Day"],
        "2024-06-03": ["Birth Anniversary of Harilal Upadhyay", "Event: World Bicycle Day"],
        "2024-06-04": ["Birth Anniversary of Basava Premanand", "Event: International Day of Innocent Children Victims of Aggression"],
        "2024-06-05": ["Birth Anniversary of Jagjivan Ram", "Event: World Environment Day"],
        "2024-06-06": ["Birth Anniversary of Gopinath Bordoloi", "Event: Russian Language Day"],
        "2024-06-07": ["Birth Anniversary of Ananda Mohan Bose", "Event: World Food Safety Day"],
        "2024-06-08": ["Birth Anniversary of Shriya Bhupal", "Event: World Oceans Day"],
        "2024-06-09": ["Birth Anniversary of Birsa Munda", "Event: International Archives Day"],
        "2024-06-10": ["Birth Anniversary of Feroze Gandhi", "Event: World Art Nouveau Day"],
        "2024-06-11": ["Birth Anniversary of Abdul Kalam Azad", "Event: International Day of Yoga Preparation"],
        "2024-06-12": ["Birth Anniversary of Dhondo Keshav Karve", "Event: World Day Against Child Labour"],
        "2024-06-13": ["Birth Anniversary of Nandini Satpathy", "Event: International Albinism Awareness Day"],
        "2024-06-14": ["Birth Anniversary of V. O. Chidambaram Pillai", "Event: World Blood Donor Day"],
        "2024-06-15": ["Birth Anniversary of Subramania Bharati", "Event: World Elder Abuse Awareness Day"],
        "2024-06-16": ["Birth Anniversary of Kuppali Venkatappa Puttappa (Kuvempu)", "Event: Father's Day"],
        "2024-06-17": ["Birth Anniversary of Bishnu Prasad Rabha", "Event: World Day to Combat Desertification and Drought"],
        "2024-06-18": ["Birth Anniversary of Jayaprakash Narayan", "Event: Autistic Pride Day"],
        "2024-06-19": ["Birth Anniversary of Sarojini Naidu", "Event: World Sickle Cell Day"],
        "2024-06-20": ["Birth Anniversary of Vishnu Ganesh Pingle", "Event: World Refugee Day"],
        "2024-06-21": ["Birth Anniversary of Uday Shankar", "Event: International Day of Yoga"],
        "2024-06-22": ["Birth Anniversary of Guru Ghasidas", "Event: World Rainforest Day"],
        "2024-06-23": ["Birth Anniversary of Chidambaram Subramaniam", "Event: United Nations Public Service Day"],
        "2024-06-24": ["Birth Anniversary of Karpoor Chandra Kulish", "Event: International Fairy Day"],
        "2024-06-25": ["Birth Anniversary of Krishna Raja Wadiyar IV", "Event: World Vitiligo Day"],
        "2024-06-26": ["Birth Anniversary of Madan Mohan Malaviya", "Event: International Day Against Drug Abuse and Illicit Trafficking"],
        "2024-06-27": ["Birth Anniversary of Aruna Asaf Ali", "Event: Micro-, Small and Medium-sized Enterprises Day"],
        "2024-06-28": ["Birth Anniversary of P. V. Narasimha Rao", "Event: International Body Piercing Day"],
        "2024-06-29": ["Birth Anniversary of Maharana Pratap", "Event: International Day of the Tropics"],
        "2024-06-30": ["Birth Anniversary of Rajendra Prasad", "Event: World Asteroid Day"],
      
        "2024-07-01": ["Birth Anniversary of Vasantrao Naik", "Event: National Doctor's Day"],
        "2024-07-02": ["Birth Anniversary of Lachit Borphukan", "Event: World UFO Day"],
        "2024-07-03": ["Birth Anniversary of Bal Gangadhar Tilak", "Event: International Plastic Bag Free Day"],
        "2024-07-04": ["Birth Anniversary of Swami Vivekananda", "Event: USA Independence Day"],
        "2024-07-05": ["Birth Anniversary of Swami Abhedananda", "Event: World Bikini Day"],
        "2024-07-06": ["Birth Anniversary of Syama Prasad Mukherjee", "Event: World Zoonoses Day"],
        "2024-07-07": ["Birth Anniversary of Chattrapati Shahuji Maharaj", "Event: Global Forgiveness Day"],
        "2024-07-08": ["Birth Anniversary of Neelam Sanjiva Reddy", "Event: World Chocolate Day"],
        "2024-07-09": ["Birth Anniversary of Guru Gobind Singh", "Event: Guru Purnima"],
        "2024-07-10": ["Birth Anniversary of Sunil Dutt", "Event: World Population Day"],
        "2024-07-11": ["Birth Anniversary of Kalpana Chawla", "Event: World Malala Day"],
        "2024-07-12": ["Birth Anniversary of Malala Yousafzai", "Event: National Simplicity Day"],
        "2024-07-13": ["Birth Anniversary of Chittaranjan Das", "Event: World Rock Day"],
        "2024-07-14": ["Birth Anniversary of H. S. Bhabha", "Event: Bastille Day"],
        "2024-07-15": ["Birth Anniversary of K. Kamaraj", "Event: World Youth Skills Day"],
        "2024-07-16": ["Birth Anniversary of Aruna Asaf Ali", "Event: World Snake Day"],
        "2024-07-17": ["Birth Anniversary of Kamaladevi Chattopadhyay", "Event: World Day for International Justice"],
        "2024-07-18": ["Birth Anniversary of Nelson Mandela", "Event: Nelson Mandela International Day"],
        "2024-07-19": ["Birth Anniversary of Mangal Pandey", "Event: Flitch Day"],
        "2024-07-20": ["Birth Anniversary of B. G. Kher", "Event: International Chess Day"],
        "2024-07-21": ["Birth Anniversary of Hakim Ajmal Khan", "Event: National Junk Food Day"],
        "2024-07-22": ["Birth Anniversary of Laxmi Mall Singhvi", "Event: Pi Approximation Day"],
        "2024-07-23": ["Birth Anniversary of Bal Gangadhar Tilak", "Event: National Refreshment Day"],
        "2024-07-24": ["Birth Anniversary of Guru Harkrishan", "Event: National Thermal Engineer Day"],
        "2024-07-25": ["Birth Anniversary of Ved Mehta", "Event: National Parents Day"],
        "2024-07-26": ["Birth Anniversary of Satish Dhawan", "Event: Kargil Vijay Diwas"],
        "2024-07-27": ["Birth Anniversary of A. P. J. Abdul Kalam", "Event: World Hepatitis Day"],
        "2024-07-28": ["Birth Anniversary of Beant Singh", "Event: World Nature Conservation Day"],
        "2024-07-29": ["Birth Anniversary of J. R. D. Tata", "Event: International Tiger Day"],
        "2024-07-30": ["Birth Anniversary of Munshi Premchand", "Event: World Day Against Trafficking in Persons"],
        "2024-07-31": ["Birth Anniversary of Muhammad Rafi", "Event: International Ranger Day"],
      
        "2024-08-01": ["Birth Anniversary of Kamala Nehru", "Event: National Mountain Climbing Day"],
        "2024-08-02": ["Birth Anniversary of Pingali Venkayya", "Event: International Friendship Day"],
        "2024-08-03": ["Birth Anniversary of Bal Gangadhar Tilak", "Event: National Watermelon Day"],
        "2024-08-04": ["Birth Anniversary of Kishore Kumar", "Event: Coast Guard Day"],
        "2024-08-05": ["Birth Anniversary of Maulana Azad", "Event: International Beer Day"],
        "2024-08-06": ["Birth Anniversary of Chandra Shekhar Azad", "Event: Hiroshima Day"],
        "2024-08-07": ["Birth Anniversary of Rabindranath Tagore", "Event: National Handloom Day"],
        "2024-08-08": ["Birth Anniversary of Subhas Chandra Bose", "Event: Quit India Movement Day"],
        "2024-08-09": ["Birth Anniversary of Vinoba Bhave", "Event: International Day of the World's Indigenous Peoples"],
        "2024-08-10": ["Birth Anniversary of Jagjivan Ram", "Event: World Lion Day"],
        "2024-08-11": ["Birth Anniversary of Vikram Sarabhai", "Event: Raksha Bandhan"],
        "2024-08-12": ["Birth Anniversary of Dhirubhai Ambani", "Event: International Youth Day"],
        "2024-08-13": ["Birth Anniversary of Surendranath Banerjee", "Event: World Organ Donation Day"],
        "2024-08-14": ["Birth Anniversary of Chhavi Rajawat", "Event: Pakistan Independence Day"],
        "2024-08-15": ["Birth Anniversary of Aurobindo Ghose", "Event: India Independence Day"],
        "2024-08-16": ["Birth Anniversary of Rajiv Gandhi", "Event: Parsi New Year"],
        "2024-08-17": ["Birth Anniversary of Ustad Bismillah Khan", "Event: Indonesian Independence Day"],
        "2024-08-18": ["Birth Anniversary of Amrita Pritam", "Event: Bad Poetry Day"],
        "2024-08-19": ["Birth Anniversary of M. G. Ramachandran", "Event: World Photography Day"],
        "2024-08-20": ["Birth Anniversary of H. P. Nanda", "Event: Sadbhavana Diwas"],
        "2024-08-21": ["Birth Anniversary of Kishore Kumar", "Event: Senior Citizens Day"],
        "2024-08-22": ["Birth Anniversary of Pranab Mukherjee", "Event: World Plant Milk Day"],
        "2024-08-23": ["Birth Anniversary of Bismillah Khan", "Event: International Day for the Remembrance of the Slave Trade and its Abolition"],
        "2024-08-24": ["Birth Anniversary of Shivaram Rajguru", "Event: Vesuvius Day"],
        "2024-08-25": ["Birth Anniversary of Mother Teresa", "Event: National Banana Split Day"],
        "2024-08-26": ["Birth Anniversary of Harivansh Rai Bachchan", "Event: Women's Equality Day"],
        "2024-08-27": ["Birth Anniversary of M. S. Swaminathan", "Event: National Just Because Day"],
        "2024-08-28": ["Birth Anniversary of Dhyan Chand", "Event: National Bow Tie Day"],
        "2024-08-29": ["Birth Anniversary of Major Dhyan Chand", "Event: National Sports Day"],
        "2024-08-30": ["Birth Anniversary of V. V. Giri", "Event: Small Industry Day"],
        "2024-08-31": ["Birth Anniversary of Amrita Sher-Gil", "Event: Hari Merdeka (Malaysia)"],
      
        "2024-09-01": ["Birth Anniversary of C. N. Annadurai", "Event: World Letter Writing Day", "HOMEWORK: Complete WS no 23 and write all the answers in the homework notebook."],
        "2024-09-02": ["Birth Anniversary of P. A. Sangma", "Event: Coconut Day"],
        "2024-09-03": ["Birth Anniversary of Rajendra Prasad", "Event: Skyscraper Day"],
        "2024-09-04": ["Birth Anniversary of Rishi Kapoor", "Event: World Beard Day"],
        "2024-09-05": ["Birth Anniversary of Dr. Sarvepalli Radhakrishnan", "Event: Teacher's Day"],
        "2024-09-06": ["Birth Anniversary of Lata Mangeshkar", "Event: Read a Book Day"],
        "2024-09-07": ["Birth Anniversary of E. M. S. Namboodiripad", "Event: Brazil Independence Day"],
        "2024-09-08": ["Birth Anniversary of Bhupen Hazarika", "Event: International Literacy Day"],
        "2024-09-09": ["Birth Anniversary of Akkineni Nageswara Rao", "Event: World First Aid Day"],
        "2024-09-10": ["Birth Anniversary of Rakesh Sharma", "Event: World Suicide Prevention Day"],
        "2024-09-11": ["Birth Anniversary of Vinoba Bhave", "Event: Patriot Day (USA)"],
        "2024-09-12": ["Birth Anniversary of Govind Ballabh Pant", "Event: National Day of Encouragement"],
        "2024-09-13": ["Birth Anniversary of Amrita Sher-Gil", "Event: Programmer's Day"],
        "2024-09-14": ["Birth Anniversary of M. Visvesvaraya", "Event: Hindi Diwas"],
        "2024-09-15": ["Birth Anniversary of Sarvepalli Radhakrishnan", "Event: International Day of Democracy"],
        "2024-09-16": ["Birth Anniversary of M. S. Subbulakshmi", "Event: World Ozone Day"],
        "2024-09-17": ["Birth Anniversary of Periyar E. V. Ramasamy", "Event: World Patient Safety Day"],
        "2024-09-18": ["Birth Anniversary of Jiddu Krishnamurti", "Event: World Bamboo Day"],
        "2024-09-19": ["Birth Anniversary of Dr. Radha Krishnan", "Event: International Talk Like a Pirate Day"],
        "2024-09-20": ["Birth Anniversary of Sri Aurobindo", "Event: Rosh Hashanah Begins"],
        "2024-09-21": ["Birth Anniversary of Indira Gandhi", "Event: International Day of Peace"],
        "2024-09-22": ["Birth Anniversary of Fakhruddin Ali Ahmed", "Event: World Rhino Day"],
        "2024-09-23": ["Birth Anniversary of H. D. Deve Gowda", "Event: First Day of Autumn"],
        "2024-09-24": ["Birth Anniversary of Raja Ram Mohan Roy", "Event: World Maritime Day"],
        "2024-09-25": ["Birth Anniversary of P. V. Narasimha Rao", "Event: World Pharmacist Day"],
        "2024-09-26": ["Birth Anniversary of Mahatma Gandhi", "Event: World Environmental Health Day"],
        "2024-09-27": ["Birth Anniversary of Lala Lajpat Rai", "Event: World Tourism Day"],
        "2024-09-28": ["Birth Anniversary of Bhagat Singh", "Event: World Rabies Day"],
        "2024-09-29": ["Birth Anniversary of Dr. Manmohan Singh", "Event: World Heart Day"],
        "2024-09-30": ["Birth Anniversary of Madan Mohan Malaviya", "Event: International Translation Day"],
      
        "2024-10-01": ["Birth Anniversary of A. K. Antony", "Event: International Day of Older Persons"],
        "2024-10-02": ["Birth Anniversary of Mahatma Gandhi", "Event: Gandhi Jayanti", "Event: International Day of Non-Violence"],
        "2024-10-03": ["Birth Anniversary of T. N. Seshan", "Event: World Habitat Day"],
        "2024-10-04": ["Birth Anniversary of Lal Bahadur Shastri", "Event: World Animal Day"],
        "2024-10-05": ["Birth Anniversary of B. R. Ambedkar", "Event: World Teachers' Day"],
        "2024-10-06": ["Birth Anniversary of Rajendra Prasad", "Event: World Cerebral Palsy Day"],
        "2024-10-07": ["Birth Anniversary of Birsa Munda", "Event: World Cotton Day"],
        "2024-10-08": ["Birth Anniversary of Jayaprakash Narayan", "Event: Indian Air Force Day"],
        "2024-10-09": ["Birth Anniversary of Narendra Modi", "Event: World Post Day"],
        "2024-10-10": ["Birth Anniversary of K. R. Narayanan", "Event: World Mental Health Day"],
        "2024-10-11": ["Birth Anniversary of Amitabh Bachchan", "Event: International Day of the Girl Child"],
        "2024-10-12": ["Birth Anniversary of Homi J. Bhabha", "Event: World Arthritis Day"],
        "2024-10-13": ["Birth Anniversary of Nana Patekar", "Event: International Day for Disaster Reduction"],
        "2024-10-14": ["Birth Anniversary of Nargis Dutt", "Event: World Standards Day"],
        "2024-10-15": ["Birth Anniversary of Dr. A. P. J. Abdul Kalam", "Event: Global Handwashing Day"],
        "2024-10-16": ["Birth Anniversary of Hema Malini", "Event: World Food Day"],
        "2024-10-17": ["Birth Anniversary of Smita Patil", "Event: International Day for the Eradication of Poverty"],
        "2024-10-18": ["Birth Anniversary of Om Puri", "Event: World Menopause Day"],
        "2024-10-19": ["Birth Anniversary of Kamal Haasan", "Event: World Pediatric Bone and Joint Day"],
        "2024-10-20": ["Birth Anniversary of N. T. Rama Rao", "Event: World Osteoporosis Day"],
        "2024-10-21": ["Birth Anniversary of Shammi Kapoor", "Event: Police Commemoration Day"],
        "2024-10-22": ["Birth Anniversary of Kader Khan", "Event: International Stuttering Awareness Day"],
        "2024-10-23": ["Birth Anniversary of Amjad Khan", "Event: Mole Day"],
        "2024-10-24": ["Birth Anniversary of Ustad Bismillah Khan", "Event: United Nations Day"],
        "2024-10-25": ["Birth Anniversary of Laxmi Chhaya", "Event: World Pasta Day"],
        "2024-10-26": ["Birth Anniversary of Homi J. Bhabha", "Event: International Day of Intersex Awareness"],
        "2024-10-27": ["Birth Anniversary of Yash Chopra", "Event: World Day for Audiovisual Heritage"],
        "2024-10-28": ["Birth Anniversary of Indira Gandhi", "Event: International Animation Day"],
        "2024-10-29": ["Birth Anniversary of Feroze Gandhi", "Event: World Psoriasis Day"],
        "2024-10-30": ["Birth Anniversary of Guru Nanak", "Event: World Savings Day"],
        "2024-10-31": ["Birth Anniversary of Sardar Vallabhbhai Patel", "Event: National Unity Day"],
      
        "2024-11-01": ["Birth Anniversary of P. V. Narasimha Rao", "Event: Karnataka Rajyotsava"],
        "2024-11-02": ["Birth Anniversary of Shahrukh Khan", "Event: International Day to End Impunity for Crimes Against Journalists"],
        "2024-11-03": ["Birth Anniversary of Lakshmi Sahgal", "Event: World Jellyfish Day"],
        "2024-11-04": ["Birth Anniversary of A. C. Bhaktivedanta Swami Prabhupada", "Event: Diwali"],
        "2024-11-05": ["Birth Anniversary of Bhupen Hazarika", "Event: Guy Fawkes Night"],
        "2024-11-06": ["Birth Anniversary of C. V. Raman", "Event: World Day to Protect the Environment in War"],
        "2024-11-07": ["Birth Anniversary of Anwar Ibrahim", "Event: National Cancer Awareness Day"],
        "2024-11-08": ["Birth Anniversary of T. S. Eliot", "Event: World Radiography Day"],
        "2024-11-09": ["Birth Anniversary of Homi Bhabha", "Event: Legal Services Day"],
        "2024-11-10": ["Birth Anniversary of Abdul Kalam", "Event: World Science Day for Peace and Development"],
        "2024-11-11": ["Birth Anniversary of Maulana Abul Kalam Azad", "Event: National Education Day"],
        "2024-11-12": ["Birth Anniversary of Dr. Sun Yat-sen", "Event: World Pneumonia Day"],
        "2024-11-13": ["Birth Anniversary of Jawaharlal Nehru", "Event: World Kindness Day"],
        "2024-11-14": ["Birth Anniversary of Jawaharlal Nehru", "Event: Children's Day"],
        "2024-11-15": ["Birth Anniversary of Birsa Munda", "Event: Jharkhand Foundation Day"],
        "2024-11-16": ["Birth Anniversary of Shahu Maharaj", "Event: International Day for Tolerance"],
        "2024-11-17": ["Birth Anniversary of V. Shantaram", "Event: International Students' Day"],
        "2024-11-18": ["Birth Anniversary of Ramakrishna Paramahamsa", "Event: National Epilepsy Day"],
        "2024-11-19": ["Birth Anniversary of Indira Gandhi", "Event: International Men's Day"],
        "2024-11-20": ["Birth Anniversary of Rani Lakshmibai", "Event: Universal Children's Day"],
        "2024-11-21": ["Birth Anniversary of Satyajit Ray", "Event: World Television Day"],
        "2024-11-22": ["Birth Anniversary of Guru Nanak Dev", "Event: International Music Day"],
        "2024-11-23": ["Birth Anniversary of J. C. Bose", "Event: Fibonacci Day"],
        "2024-11-24": ["Birth Anniversary of Rukmini Devi Arundale", "Event: Guru Tegh Bahadur's Martyrdom Day"],
        "2024-11-25": ["Birth Anniversary of Dinkar Kaushik", "Event: International Day for the Elimination of Violence against Women"],
        "2024-11-26": ["Birth Anniversary of Dr. Verghese Kurien", "Event: Constitution Day"],
        "2024-11-27": ["Birth Anniversary of Prithviraj Kapoor", "Event: National Organ Donation Day"],
        "2024-11-28": ["Birth Anniversary of Raja Ram Mohan Roy", "Event: Thanksgiving Day"],
        "2024-11-29": ["Birth Anniversary of K. P. Hegde", "Event: International Day of Solidarity with the Palestinian People"],
        "2024-11-30": ["Birth Anniversary of Jagdish Chandra Bose", "Event: St. Andrew's Day"],
      
        "2024-12-01": ["Birth Anniversary of N. G. Ranga", "Event: World AIDS Day"],
        "2024-12-02": ["Birth Anniversary of Bhopal Gas Tragedy Victims", "Event: National Pollution Control Day"],
        "2024-12-03": ["Birth Anniversary of Rajendra Prasad", "Event: International Day of Persons with Disabilities"],
        "2024-12-4": ["Birth Anniversary of R. Venkataraman", "Event: Indian Navy Day"],
        "2024-12-05": ["Birth Anniversary of N. S. Krishnan", "Event: World Soil Day"],
        "2024-12-06": ["Birth Anniversary of B. R. Ambedkar", "Event: Mahaparinirvan Diwas"],
        "2024-12-07": ["Birth Anniversary of Raj Kapoor", "Event: Armed Forces Flag Day"],
        "2024-12-08": ["Birth Anniversary of Shatrughan Sinha", "Event: Bodhi Day"],
        "2024-12-09": ["Birth Anniversary of Amartya Sen", "Event: International Anti-Corruption Day"],
        "2024-12-10": ["Birth Anniversary of C. Rajagopalachari", "Event: Human Rights Day"],
        "2024-12-11": ["Birth Anniversary of Dilip Kumar", "Event: International Mountain Day"],
        "2024-12-12": ["Birth Anniversary of Rajinikanth", "Event: Universal Health Coverage Day"],
        "2024-12-13": ["Birth Anniversary of Ravi Shankar", "Event: National Cocoa Day"],
        "2024-12-14": ["Birth Anniversary of Raj Kapoor", "Event: National Energy Conservation Day"],
        "2024-12-15": ["Birth Anniversary of S. V. Ranga Rao", "Event: International Tea Day"],
        "2024-12-16": ["Birth Anniversary of Ustad Bismillah Khan", "Event: Vijay Diwas"],
        "2024-12-17": ["Birth Anniversary of Baba Amte", "Event: Wright Brothers Day"],
        "2024-12-18": ["Birth Anniversary of K. M. Munshi", "Event: International Migrants Day"],
        "2024-12-19": ["Birth Anniversary of Kuldip Nayar", "Event: Goa Liberation Day"],
        "2024-12-20": ["Birth Anniversary of Sushma Swaraj", "Event: International Human Solidarity Day"],
        "2024-12-21": ["Birth Anniversary of Madan Mohan Malaviya", "Event: National Crossword Puzzle Day"],
        "2024-12-22": ["Birth Anniversary of Srinivasa Ramanujan", "Event: National Mathematics Day"],
        "2024-12-23": ["Birth Anniversary of Choudhary Charan Singh", "Event: Kisan Diwas"],
        "2024-12-24": ["Birth Anniversary of Mohammad Hidayatullah", "Event: National Consumer Rights Day"],
        "2024-12-25": ["Birth Anniversary of Atal Bihari Vajpayee", "Event: Christmas Day"],
        "2024-12-26": ["Birth Anniversary of Albert Ekka", "Event: Boxing Day"],
        "2024-12-27": ["Birth Anniversary of Mirza Ghalib", "Event: International Day of Epidemic Preparedness"],
        "2024-12-28": ["Birth Anniversary of Ratan Tata", "Event: Holy Innocents' Day"],
        "2024-12-29": ["Birth Anniversary of Rajesh Khanna", "Event: International Cello Day"],
        "2024-12-30": ["Birth Anniversary of Rudyard Kipling", "Event: Bacon Day"],
        "2024-12-31": ["Birth Anniversary of Salim Ali", "Event: New Year's Eve"],
      
        "2025-01-01": ["Birth Anniversary of Vidyasagar", "Event: New Year's Day"],
        "2025-01-02": ["Birth Anniversary of Mannathu Padmanabha Pillai", "Event: National Science Fiction Day"],
        "2025-01-03": ["Birth Anniversary of Savitribai Phule", "Event: J. R. R. Tolkien Day"],
        "2025-01-04": ["Birth Anniversary of Louis Braille", "Event: World Braille Day"],
        "2025-01-05": ["Birth Anniversary of Maharana Pratap", "Event: National Bird Day"],
        "2025-01-06": ["Birth Anniversary of K. M. Panikkar", "Event: Epiphany"],
        "2025-01-07": ["Birth Anniversary of Satyendra Nath Bose", "Event: Orthodox Christmas Day"],
        "2025-01-08": ["Birth Anniversary of Stephen Hawking", "Event: Elvis Presley's Birthday"],
        "2025-01-09": ["Birth Anniversary of Har Gobind Khorana", "Event: NRI Day"],
        "2025-01-10": ["Birth Anniversary of Hrithik Roshan", "Event: World Hindi Day"],
        "2025-01-11": ["Birth Anniversary of Lal Bahadur Shastri", "Event: National Human Trafficking Awareness Day"],
        "2025-01-12": ["Birth Anniversary of Swami Vivekananda", "Event: National Youth Day"],
        "2025-01-13": ["Birth Anniversary of Guru Gobind Singh", "Event: Lohri"],
        "2025-01-14": ["Birth Anniversary of Mahatma Gandhi", "Event: Makar Sankranti"],
        "2025-01-15": ["Birth Anniversary of K. Kamaraj", "Event: Pongal"],
        "2025-01-16": ["Birth Anniversary of C. Rajagopalachari", "Event: National Religious Freedom Day"],
        "2025-01-17": ["Birth Anniversary of Muhammad Ali", "Event: Benjamin Franklin's Birthday"],
        "2025-01-18": ["Birth Anniversary of N. T. Rama Rao", "Event: Martin Luther King Jr. Day"],
        "2025-01-19": ["Birth Anniversary of Dr. Radhakrishnan", "Event: World Religion Day"],
        "2025-01-20": ["Birth Anniversary of Srinivasa Ramanujan", "Event: Inauguration Day"],
        "2025-01-21": ["Birth Anniversary of Subhas Chandra Bose", "Event: National Hugging Day"],
        "2025-01-22": ["Birth Anniversary of J. Krishnamurti", "Event: Roe v. Wade Anniversary"],
        "2025-01-23": ["Birth Anniversary of Subhas Chandra Bose", "Event: National Pie Day"],
        "2025-01-24": ["Birth Anniversary of Charan Singh", "Event: International Day of Education"],
        "2025-01-25": ["Birth Anniversary of K. M. Munshi", "Event: National Voters Day"],
        "2025-01-26": ["Birth Anniversary of Lala Lajpat Rai", "Event: Republic Day"],
        "2025-01-27": ["Birth Anniversary of Lewis Carroll", "Event: International Holocaust Remembrance Day"],
        "2025-01-28": ["Birth Anniversary of Lala Lajpat Rai", "Event: Data Privacy Day"],
        "2025-01-29": ["Birth Anniversary of Bal Thackeray", "Event: National Puzzle Day"],
        "2025-01-30": ["Birth Anniversary of Mahatma Gandhi", "Event: Martyr's Day"],
        "2025-01-31": ["Birth Anniversary of Dr. Harivansh Rai Bachchan", "Event: Inspire Your Heart with Art Day"],
            "2025-02-01": ["Birth Anniversary of M. N. Roy", "Event: Indian Coast Guard Day"],
            "2025-02-02": ["Birth Anniversary of Khushwant Singh", "Event: World Wetlands Day"],
            "2025-02-03": ["Birth Anniversary of Maulana Abul Kalam Azad", "Event: World Cancer Day"],
            "2025-02-04": ["Birth Anniversary of Bhikaiji Cama", "Event: World Cancer Day"],
            "2025-02-05": ["Birth Anniversary of Zakir Hussain", "Event: Safer Internet Day"],
            "2025-02-06": ["Birth Anniversary of Kavi Pradeep", "Event: International Day of Zero Tolerance for Female Genital Mutilation"],
            "2025-02-07": ["Birth Anniversary of Subhas Chandra Bose", "Event: Rose Day"],
            "2025-02-08": ["Birth Anniversary of Jagjivan Ram", "Event: Propose Day"],
            "2025-02-09": ["Birth Anniversary of Gopalaswami Ayyangar", "Event: Chocolate Day"],
            "2025-02-10": ["Birth Anniversary of Harivansh Rai Bachchan", "Event: Teddy Day"],
            "2025-02-11": ["Birth Anniversary of Sarojini Naidu", "Event: Promise Day"],
            "2025-02-12": ["Birth Anniversary of Sarvepalli Radhakrishnan", "Event: Hug Day"],
            "2025-02-13": ["Birth Anniversary of Chhatrapati Shivaji Maharaj", "Event: Kiss Day"],
            "2025-02-14": ["Birth Anniversary of Madhavrao Scindia", "Event: Valentine's Day"],
            "2025-02-15": ["Birth Anniversary of Satyajit Ray", "Event: International Childhood Cancer Day"],
            "2025-02-16": ["Birth Anniversary of Gopal Krishna Gokhale", "Event: World Pangolin Day"],
            "2025-02-17": ["Birth Anniversary of Kavi Pradeep", "Event: Random Acts of Kindness Day"],
            "2025-02-18": ["Birth Anniversary of Ramakrishna Paramahamsa", "Event: Pluto Day"],
            "2025-02-19": ["Birth Anniversary of Shivaji Maharaj", "Event: World Whale Day"],
            "2025-02-20": ["Birth Anniversary of S. V. Ranga Rao", "Event: World Day of Social Justice"],
            "2025-02-21": ["Birth Anniversary of Dev Anand", "Event: International Mother Language Day"],
            "2025-02-22": ["Birth Anniversary of Kasturba Gandhi", "Event: World Thinking Day"],
            "2025-02-23": ["Birth Anniversary of Vijay Hazare", "Event: International Dog Biscuit Appreciation Day"],
            "2025-02-24": ["Birth Anniversary of Jayalalithaa", "Event: Central Excise Day"],
            "2025-02-25": ["Birth Anniversary of J. P. Narayan", "Event: Quiet Day"],
            "2025-02-26": ["Birth Anniversary of A. R. Rahman", "Event: Tell a Fairy Tale Day"],
            "2025-02-27": ["Birth Anniversary of Morarji Desai", "Event: World NGO Day"],
            "2025-02-28": ["Birth Anniversary of C. V. Raman", "Event: National Science Day"],
            "2025-03-01": ["Birth Anniversary of Swami Dayananda Saraswati", "Event: Zero Discrimination Day"],
            "2025-03-02": ["Birth Anniversary of Bedabrata Barua", "Event: Employee Appreciation Day"],
            "2025-03-03": ["Birth Anniversary of Jamnalal Bajaj", "Event: World Wildlife Day"],
            "2025-03-04": ["Birth Anniversary of K. M. Cariappa", "Event: National Safety Day"],
            "2025-03-05": ["Birth Anniversary of Momofuku Ando", "Event: World Book Day"],
            "2025-03-06": ["Birth Anniversary of Dr. M. S. Swaminathan", "Event: European Day of the Righteous"],
            "2025-03-07": ["Birth Anniversary of Kalpana Chawla", "Event: International Women's Day"],
            "2025-03-08": ["Birth Anniversary of Sahir Ludhianvi", "Event: International Women's Day"],
            "2025-03-09": ["Birth Anniversary of Dr. Zakir Husain", "Event: World Kidney Day"],
            "2025-03-10": ["Birth Anniversary of Birbal Sahni", "Event: Mario Day"],
            "2025-03-11": ["Birth Anniversary of Tanaji Malusare", "Event: World Plumbing Day"],
            "2025-03-12": ["Birth Anniversary of S. P. Balasubrahmanyam", "Event: World Day Against Cyber Censorship"],
            "2025-03-13": ["Birth Anniversary of A. K. Gopalan", "Event: World Sleep Day"],
            "2025-03-14": ["Birth Anniversary of Albert Einstein", "Event: Pi Day"],
            "2025-03-15": ["Birth Anniversary of Joseph Baptista", "Event: World Consumer Rights Day"],
            "2025-03-16": ["Birth Anniversary of Madhavrao Scindia", "Event: Panda Day"],
            "2025-03-17": ["Birth Anniversary of Kalpana Chawla", "Event: St. Patrick's Day"],
            "2025-03-18": ["Birth Anniversary of Mangal Pandey", "Event: Global Recycling Day"],
            "2025-03-19": ["Birth Anniversary of Subrahmanyan Chandrasekhar", "Event: World Sparrow Day"],
            "2025-03-20": ["Birth Anniversary of Prithviraj Kapoor", "Event: International Day of Happiness"],
            "2025-03-21": ["Birth Anniversary of Nirmala Deshpande", "Event: World Down Syndrome Day"],
            "2025-03-22": ["Birth Anniversary of Surya Sen", "Event: World Water Day"],
            "2025-03-23": ["Birth Anniversary of Bhagat Singh", "Event: Martyrs' Day"],
            "2025-03-24": ["Birth Anniversary of B. R. Ambedkar", "Event: World Tuberculosis Day"],
            "2025-03-25": ["Birth Anniversary of Ravi Shankar", "Event: International Day of Remembrance of the Victims of Slavery and the Transatlantic Slave Trade"],
            "2025-03-26": ["Birth Anniversary of Usha Mehta", "Event: Purple Day"],
            "2025-03-27": ["Birth Anniversary of Amrita Pritam", "Event: World Theatre Day"],
            "2025-03-28": ["Birth Anniversary of Narendra Modi", "Event: Respect Your Cat Day"],
            "2025-03-29": ["Birth Anniversary of R. K. Narayan", "Event: Earth Hour"],
            "2025-03-30": ["Birth Anniversary of Vinoba Bhave", "Event: Doctors' Day"],
            "2025-03-31": ["Birth Anniversary of Taraknath Das", "Event: International Transgender Day of Visibility"],
            "2025-04-01": ["Birth Anniversary of Ustad Allauddin Khan", "Event: April Fool's Day"],
            "2025-04-02": ["Birth Anniversary of Ashok Kumar", "Event: World Autism Awareness Day"],
            "2025-04-03": ["Birth Anniversary of Gopabandhu Das", "Event: World Party Day"],
            "2025-04-04": ["Birth Anniversary of C. Rajagopalachari", "Event: International Day for Mine Awareness and Assistance in Mine Action"],
            "2025-04-05": ["Birth Anniversary of Dadasaheb Phalke", "Event: National Maritime Day"],
            "2025-04-06": ["Birth Anniversary of A. K. Hangal", "Event: International Day of Sport for Development and Peace"],
            "2025-04-07": ["Birth Anniversary of Pandit Ravi Shankar", "Event: World Health Day"],
            "2025-04-08": ["Birth Anniversary of Lakshmi Sahgal", "Event: International Romani Day"],
            "2025-04-09": ["Birth Anniversary of Vishnu Narayan Bhatkhande", "Event: Day of Silence"],
            "2025-04-10": ["Birth Anniversary of Bhagat Singh", "Event: World Homeopathy Day"],
            "2025-04-11": ["Birth Anniversary of Kasturba Gandhi", "Event: National Safe Motherhood Day"],
            "2025-04-12": ["Birth Anniversary of Satish Dhawan", "Event: International Day of Human Space Flight"],
            "2025-04-13": ["Birth Anniversary of Baisakhi", "Event: Jallianwala Bagh Massacre"],
            "2025-04-14": ["Birth Anniversary of B. R. Ambedkar", "Event: Ambedkar Jayanti"],
            "2025-04-15": ["Birth Anniversary of Guru Tegh Bahadur", "Event: World Art Day"],
            "2025-04-16": ["Birth Anniversary of Charlie Chaplin", "Event: World Voice Day"],
            "2025-04-17": ["Birth Anniversary of Jallianwala Bagh Massacre Victims", "Event: World Hemophilia Day"],
            "2025-04-18": ["Birth Anniversary of Sarabjit Singh", "Event: World Heritage Day"],
            "2025-04-19": ["Birth Anniversary of Chaitanya Mahaprabhu", "Event: World Liver Day"],
            "2025-04-20": ["Birth Anniversary of Raja Ravi Varma", "Event: Chinese Language Day"],
            "2025-04-21": ["Birth Anniversary of M. G. Ramachandran", "Event: National Civil Service Day"],
            "2025-04-22": ["Birth Anniversary of V. K. Krishna Menon", "Event: Earth Day"],
            "2025-04-23": ["Birth Anniversary of Kalidasa", "Event: World Book and Copyright Day"],
            "2025-04-24": ["Birth Anniversary of Sachin Tendulkar", "Event: National Panchayati Raj Day"],
            "2025-04-25": ["Birth Anniversary of Gigi Hadid", "Event: World Malaria Day"],
            "2025-04-26": ["Birth Anniversary of S. Satyamurti", "Event: World Intellectual Property Day"],
            "2025-04-27": ["Birth Anniversary of Zohra Sehgal", "Event: World Veterinary Day"],
            "2025-04-28": ["Birth Anniversary of Jayaprakash Narayan", "Event: World Day for Safety and Health at Work"],
            "2025-04-29": ["Birth Anniversary of Dadasaheb Phalke", "Event: International Dance Day"],
            "2025-04-30": ["Birth Anniversary of K. Kamraj", "Event: International Jazz Day"]
          
            
};

document.getElementById('generateBtn').addEventListener('click', generateDuties);
document.getElementById('datePicker').addEventListener('change', generateDuties);
document.getElementById('backBtn').addEventListener('click', goBack);

function generateDuties() {
    const date = document.getElementById('datePicker').value;
    const selectedClass = document.getElementById('classSelect').value;

    if (!date) {
        alert("Please select a date");
        return;
    }

    const students = studentsByClass[selectedClass];
    const shuffledStudents = students.sort(() => 0.5 - Math.random());
    const dutiesList = document.getElementById('dutiesList');
    const eventsList = document.getElementById('eventsList');
    dutiesList.innerHTML = '';
    eventsList.innerHTML = '';

    duties.forEach((duty, index) => {
        const dutyItem = document.createElement('div');
        dutyItem.className = 'duty-item';
        dutyItem.textContent = `${duty}: ${shuffledStudents[index % shuffledStudents.length]}`;
        dutiesList.appendChild(dutyItem);
    });

    if (events[date]) {
        events[date].forEach(event => {
            const eventItem = document.createElement('div');
            eventItem.className = 'event-item';
            eventItem.textContent = `Event: ${event}`;
            eventsList.appendChild(eventItem);
        });
    } else {
        const noEventItem = document.createElement('div');
        noEventItem.className = 'event-item';
        noEventItem.textContent = "No events for this date.";
        eventsList.appendChild(noEventItem);
    }

    const regeneratePanel = document.createElement('div');
    regeneratePanel.id = 'controlPanel';

    const classSelect = document.createElement('select');
    classSelect.id = 'classSelect';
    classSelect.innerHTML = `
        <option value="3">Class 3</option>
        <option value="4">Class 4</option>
        <option value="5">Class 5</option>
        <option value="6">Class 6</option>
        <option value="7">Class 7</option>
        <option value="8">Class 8</option>
    `;
    classSelect.value = selectedClass;  // Keep the selected class

    const datePicker = document.createElement('input');
    datePicker.type = 'date';
    datePicker.id = 'datePicker';
    datePicker.value = date;  // Keep the selected date

    const regenerateBtn = document.createElement('button');
    regenerateBtn.textContent = 'Re-generate Duties';
    regenerateBtn.addEventListener('click', generateDuties);

    regeneratePanel.appendChild(classSelect);
    regeneratePanel.appendChild(datePicker);
    regeneratePanel.appendChild(regenerateBtn);
    dutiesList.appendChild(regeneratePanel);

    // Show the back button after generating duties
    document.getElementById('backBtn').style.display = 'block';
}

function goBack() {
    // Clear duties and events lists
    document.getElementById('dutiesList').innerHTML = '';
    document.getElementById('eventsList').innerHTML = '';
    
    // Hide the back button
    document.getElementById('backBtn').style.display = 'none';
    
    // Reset the date picker and class selector
    document.getElementById('datePicker').value = '';
    document.getElementById('classSelect').value = '3';
}
